# Copyright (c) 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Sathish Kuttan <sathish.k.kuttan@intel.com>

general:
    name:           Sue Creek
    max_spi_speed:  9.6         # Max SPI clock frequency 9.6 MHz

rpi:
    spi:
        device:    /dev/spidev0.0

    gpio:
        reset:     22      # GPIO 22 for resetting device
        wake:      23      # GPIO 23 for wake notification to device
        irq:       27      # GPIO 27 for interrupt notification from device

upsq:
    spi:
        device:    /dev/spidev1.0

    gpio:
        reset:     431     # GPIO 431 for resetting device
        wake:      471     # GPIO 471 for wake notification to device
        irq:       432     # GPIO 432 for interrupt notification from device
